### ISSUE TITLE
Use empty: false instead of required: true

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#13]
Our implementation of `required: true` is actually the [Cerberus rule](http://docs.python-cerberus.org/en/stable/usage.html#empty) of `empty: false`. We should reuse that rule:
- For better consistency with Cerberus
- To avoid confusion as Cerberus also has a `required` rule, which validates if a certain field is present, without checking the content.

Note that `empty: true` **does not require** the column to be empty, it merely **allows** the column to be empty. If you want to **require a column to be empty**, use `allowed: ""`.

**Comment by stijnvanhoey** [comment]
Consistency with the cerberus will be aimed for and  `required` is used to test if a field (key-value) is available, as mentioned. 

Making sure a column is an empty string, `allowed: ""` can be used
To make sure a field is not an empty string, `empty: False` can be used

The previous elements need also to be complementary to testing of the data `type`, which is done first by Cerberus, leading to problems when an empty string is combined together with a datatype which is not a string:

```python
schema = {'name': {'type': 'integer'}}
document = {'name': ''}
v = DwcaValidator(schema)
v.validate(document, schema)
v.errors
>>> {'name': ["field 'name' could not be coerced", 'must be of integer type']}
```
Only the `Nullable` rule can overcome this behaviour AND by converting empty strings by `None``values:

```python
schema = {'name': {'type': 'integer', 'nullable': True}}
document = {'name': None}
v = DwcaValidator(schema)
v.validate(document, schema)
v.errors
>>> {}
```

So, in order to keep the compatibility with cerberus and taking into account the characteristics of the DwcAReader (every field is actually a string), following elements were added:
* int, float, number and boolean types in the ruleset are automatically extended with `coerce` rules, which converts the field to the given dtype; if this fails; the error message provides information about the wrong dtype
* If type information is required (float/int/boolean/number), then empty strings are converted to None values before starting the test. if at the same time, `empty : False` (empty values are not welcome) is also provided as test, this will result in errors for empty strings. If `empty : False` is not present, the test `Nullable:True` will also be added, resulting in empty strings to be accepted.

**Comment by stijnvanhoey** [comment]
Due to the sequence in how cerberus operates the nullable (rule `nullable`: True is tested in the first place, whereafter the other elements are tested), the addition of the coerce rule does not work to handle '' by converting them first to None values. Moreover, this would be a very ad-how solution.

The usage of a `oneof` (`anyof`,...) environment could provide the elements needed to facilitate this in a more generic way.

The schema provides the option of one of the options listed after the hypen:
```python
schema  ="""
        decimalLatitude:
            oneof :
                - allowed : ''
                - min : 3.
                  coerce : !!python/name:float  # needed as such to make sure Yaml converts it to the object float and not the string 'float'
                  type : float
         """

v = Validator(yaml.load(schema))
v.allow_unknown = True
```

This results in the behaviour as we want it to be:

```python
testdoc = {'decimalLatitude' : '4.'}
v.validate(testdoc)
print(v.errors)
```
No errors, the string is converted to a float value (coerce), and the resulting float value is > 3

```python
testdoc = {'decimalLatitude' : ''}
v.validate(testdoc)
print(v.errors)
```
No errors, the `allowed : ''` is active and the field passes

```python
testdoc = {'decimalLatitude' : '2.'}
v.validate(testdoc)
print(v.errors)
```
error invoked, since the resulting float value < 3 . Current error message looks as follows:

```python
{'decimalLatitude': {'oneof': 'more than one rule (or no rules) validated', 'definition 1': 'min value is 3.0', 'definition 0': 'unallowed value 2.'}}
```

Question: How to make this possible in the validator:
- use the cerberus syntax as such and document this styling in how to apply this in the settings-file?
- facilitate the handling by adding some fields automatically? Options are (can be both chosen as well): 
    * always add the oneof-structure to each of the fields; we now dwc has '' as empty values included
    * automatically add the `coerce : float` anywhere the schema has a `type : float` included (and extend this for boolean, int and number as well); we now the dwca-reader always provides strings, so conversion always needed
- ad some new/additional/adapted logic in how to set up the settings file...

**Comment by stijnvanhoey** [comment]
Alternative approach to test, taking into account that for Dwc, empty string are actually the None values, preliminar conversion of empty string to `None` values.

Using the function `empty_string_none`: the following scenario does not provide any errors:

```python
schema  ="""
                decimalLatitude:
                    type : float
                    nullable : True
                    min : 3
         """

v = DwcaValidator(yaml.load(schema))
v.allow_unknown = True

testdoc = {'decimalLatitude' : '4.'}
v.validate(empty_string_none(testdoc))
print(v.errors)

testdoc = {'decimalLatitude' : '4'}
v.validate(empty_string_none(testdoc))
print(v.errors)

testdoc = {'decimalLatitude' : ''}
v.validate(empty_string_none(testdoc))
print(v.errors)

testdoc = {'decimalLatitude' : '2.'}
v.validate(empty_string_none(testdoc))
print(v.errors)
```

similar to the previous approach, the output provides No error in the first 3 occassions and the error `{'decimalLatitude': 'min value is 3'}` for the last case, as expected. Remark that the class `DwcaValidator` is used here, which automatically adds the `coerce : float`.

**Comment by stijnvanhoey** [comment]
Currently implemented according to most recent whip specifications.
